version: '3.8'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/symfony
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./:/symfony
    container_name: ${PROJECT_NAME}-php-fpm
    depends_on:
      - postgres_db

  php-cli:
    build:
      context: ./docker/php-cli
    volumes:
      - ./:/symfony
    command: sleep 10000
    container_name: ${PROJECT_NAME}-php-cli

  node:
    image: node:15.3.0-alpine3.10
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true

  postgres_db:
    privileged: true
    image: postgres:13-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/
    container_name: ${PROJECT_NAME}-postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"

volumes:
  postgres-data: